security:
  jwt:
    secret-key: fdfedece-f45e-445e-8e54-69d781bdb0a2
    access-token-expiration-time: 900000 # 15 minutes in milliseconds
    refresh-token-expiration-time: 7889238000 # 3 months in milliseconds
current:
  environment: development
